# Generated by Django 5.1.1 on 2024-10-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandsatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cloud_coverage', models.FloatField()),
                ('sensor', models.CharField(max_length=50)),
                ('bbox', models.JSONField()),
                ('path', models.IntegerField()),
                ('row', models.IntegerField()),
                ('url', models.URLField()),
                ('metadata_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landsat Image',
                'verbose_name_plural': 'Landsat Images',
                'ordering': ['date'],
            },
        ),
    ]
