# Generated by Django 5.1.1 on 2024-10-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandsatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=100, unique=True)),
                ('bands', models.CharField(max_length=200)),
                ('cloud_coverage', models.FloatField()),
                ('capture_date', models.DateField()),
            ],
        ),
    ]
