# Generated by Django 5.1.1 on 2024-09-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandsatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(help_text='ID de la imagen en Google Earth Engine', max_length=100, unique=True)),
                ('fecha_captura', models.DateField(help_text='Fecha de captura de la imagen')),
                ('path', models.CharField(help_text='Ruta en Google Earth Engine', max_length=255)),
                ('bbox', models.JSONField(help_text='Bounding box de la imagen, almacenado como coordenadas geográficas')),
                ('bandas', models.JSONField(help_text='Bandas seleccionadas para el procesamiento')),
                ('procesado', models.BooleanField(default=False, help_text='Indica si la imagen ha sido procesada')),
                ('url_renderizada', models.URLField(blank=True, help_text='URL de la imagen renderizada')),
            ],
            options={
                'verbose_name': 'Landsat Image',
                'verbose_name_plural': 'Landsat Images',
            },
        ),
    ]
