# Generated by Django 5.1.1 on 2024-10-01 15:19

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_landsatimage'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
    ]
